### ISSUE TITLE
Creation/Editing Taskchain (49) and Moodle 3.3+

### ISSUE THREAD

**Issue by UltraFlux** [gbateson/moodle-mod_taskchain#13] opened 2017-08-28 23:08 UTC
Hi Gordon,

We have been using your plugin for a long time now and I recently completed an upgrade from 3.2 to 3.3.1 including an update of taskchain to (49) which is outlined as 3.3 compatible.

The owner of the website indicates that while existing content works fine. Creating/Editing content is no longer functional.

I have narrowed this down to newly added code in Moodle 3.3 that was not present in 3.2. Please note that this is just a basic code review but I believe this is at least one point where taskchain and moodle are failing to work together.

**LOG FILE**
`2017/08/29 00:22:37 [error] 25111#25111: *2165648 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property of non-object in /www/degrama/englishlab1.com/htdocs/mod/taskchain/edit/form/helper/record.php on line 905
PHP message: Default exception handler: Coding error detected, it must be fixed by a programmer: Invalid context id specified context::instance_by_id() Debug:
Error code: codingerror
* line 5165 of /lib/accesslib.php: coding_exception thrown
* line 956 of /lib/filelib.php: call to context::instance_by_id()
* line 905 of /mod/taskchain/edit/form/helper/record.php: call to file_save_draft_area_files()
* line 862 of /mod/taskchain/edit/form/helper/record.php: call to taskchain_form_helper_record->fix_template_filearea()
* line 1640 of /mod/taskchain/edit/form/helper/base.php: call to taskchain_form_helper_record->fix_field_sourcefile()
* line 1611 of /mod/taskchain/edit/form/helper/base.php: call to taskchain_form_helper_base->fix_field()
* line 1592 of /mod/taskchain/edit/form/helper/base.php: call to taskchain_form_helper_base->fix_section()
* line 84 of /mod/taskchain/mod_form.php: call to taskchain_form_helper_base->fix_sections()
* line 1102 of /course/moodleform_mod.php: call to mod_taskchain_mod_form" while reading response header from upstream, client: 64.114.30.66, server: englishlab1.com, request: "POST /course/modedit.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "englishlab1.com", referrer: "https://englishlab1.com/course/modedit.php?add=taskchain&type=&course=18&section=1&return=0&sr=0"`

**REVIEW OF /lib/filelib.php**
https://fossies.org/diffs/moodle/3.2.3_vs_3.3/lib/filelib.php-diff.html

**Comment by gbateson** [comment] 2017-08-29 01:42
Hi UltraFlux,
thanks for letting me know about this issue on Moodle >= 3.3.

It was caused by new method in Moodle >= 3.3 which clashed which a method name, "data_postprocessing", " that was already being used by the TaskChain module. I have renamed the TaskChain method to "form_postprocessing" and confirmed that TaskChains can now be added without error on Moodle 3.3 and Moodle 3.0.

Please update the TaskChain module on the site that reported this issue at the next convenient opportunity. I will close this issue now, but please re-open if you find that the issue is not fixed to your satisfaction.

Best regards,
Gordon

**Closed by gbateson** 2017-08-29 01:42 UTC
